<html>
    <head>
        <title>Family Donation Tool</title>
        <?php $this->assets->outputCss() ?>
        <?php $this->assets->outputJs() ?>
        <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
        <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/grids-responsive-min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <div class="pure-g" id="main">
        <?php if(in_array($this->session->userType, ["donor", "admin"])) { ?>
            <div class="pure-u-1-5 pure-md-1">
                <a href="<?php echo $this->url->get('user/logout');?>" class="pure-button">Logout</a>
            </div>
        <?php } ?>
            <div class="pure-u-1 header">
                <h1>Header Stuff Goes Here Eventually</h1>
            </div>
            <?php echo $this->getContent() ?>
        </div>
    </body>
</html>