<div class="pure-u-1">
    <h1>Welcome, <?php echo $this->session->userType ?>!</h1>
    <div class="pure-g">
        <div class="pure-u-1 pure-u-md-2-5">
            <?php $this->partial('donation/view') ?>
        </div>
        <div class="pure-u-1 pure-u-md-3-5">
            <form class="pure-form" action="<?php echo $this->url->get('admin/update');?>" method="post">
                <fieldset class="admin-fieldset">
                <p>
                The following table shows people who have promised a donation, the donation amount, whether or not you have verified the donation, and the date that the donation promise was made.
                </p>
                <p>
                When you recieve a promised donation select the appropriate "verified" checkbox and then click "Save Changes." The verified donation will then be visible on the donation tracker and the "Total Raised" will be updated to reflect the new total donations.
                </p>
                    <table class="pure-table pure-table-bordered" align="center">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Amount</th>
                                <th>Verified</th>
                                <th>Date</th>
                        </thead>
                        <tbody>
                        <?php 
                            foreach($donations as $donation) {
                                $checked = $donation->getVerified() ? 'checked' : '';
                                echo '<tr><td>';
                                echo $donation->getName();
                                echo '</td><td>';
                                echo $donation->getAmount();
                                echo '</td><td>';
                                echo '<input type="checkbox" name="' . $donation->getId() . '" value="' . $donation->getId() . '" ' . $checked . '>';
                                echo '</td><td>';
                                echo $donation->getDate();
                                echo '</td></tr>';
                            }
                        ?>
                        </tbody>
                    </table>
                    <div class="button-container">
                        <button type="submit" class="pure-button pure-button-primary">Save Changes</button>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
    <div class="pure-u-1">
    <?php
        foreach($validIds as $validId) {
            echo $validId;
            echo '<br />';
        }
    ?>
    </div>
</div>