<div class="donate">
    <form class="pure-form pure-form-aligned" method="post">
        <fieldset>
            <div class="pure-control-group">
                <label for="name">Your Name:</label>
                <input id="name" type="text" name="name" placeholder="Name">
            </div>
            <div class="pure-control-group">
                <label for="amount">Donation Amount:</label>
                <input id="amount" type="number" name="amount" min=0 step=1>
            </div>
            <div class="pure-controls">
                <button type="submit" class="pure-button pure-button-primary">Submit</button>
            </div>
        </fieldset>
    </form>
</div>