<div class="pure-g view">
    <div class="pure-u-3-5">
        <h1>Total Raised:</h1>
    </div>
    <div class="pure-u-2-5 totalAmount">
        <h1>$<?php echo $confirmed ?></h1>
    </div>

    <div class="pure-u-2-3 markers">
        <div id="markerTop">$<?php echo $goal ?></div>
        <div id="marker2">$<?php echo $goal * (2/3) ?></div>
        <div id="marker1">$<?php echo $goal * (1/3) ?></div>
    </div>
    <div class="pure-u-1-3">
        <div id="donationTracker">
            <div id="donationPromised"></div>
            <div id="donationConfirmed"></div>
        </div>
    </div>
</div>

<span id="goal" hidden="hidden"><?php echo $goal ?></span>
<span id="confirmed" hidden="hidden"><?php echo $confirmed ?></span>
<span id="promised" hidden="hidden"><?php echo $promised ?></span>